# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100, unique=True)),
                ('upwd', models.CharField(max_length=200)),
                ('uemail', models.CharField(max_length=100)),
                ('ureceive', models.CharField(default='', max_length=100)),
                ('uaddress', models.CharField(default='', max_length=100)),
                ('uzipcode', models.CharField(default='', max_length=6)),
                ('uphone', models.CharField(default='', max_length=11)),
            ],
        ),
    ]
