# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=100, unique=True)),
                ('gpic', models.ImageField(upload_to='img/goods')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gunit', models.CharField(default='500g', max_length=20)),
                ('gclick', models.IntegerField(default=0)),
                ('gintroduction', models.CharField(max_length=200)),
                ('gstock', models.IntegerField(default=0)),
                ('gcontent', tinymce.models.HTMLField()),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goods_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20, unique=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='goods_info',
            name='gtypeinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_types'),
        ),
    ]
