# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.IntegerField()),
                ('goodsinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_info')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('odate', models.DateTimeField(auto_now_add=True)),
                ('oispay', models.BooleanField(default=False)),
                ('ottotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oaddress', models.CharField(max_length=150)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='orderinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo'),
        ),
    ]
